target 'iosApp' do
    use_frameworks!
    platform :ios, '14.1'

    pod 'shared', :path => '../shared'

    pod 'FirebaseMessaging'
    pod 'FirebaseAnalytics'
    pod 'FirebaseCrashlytics'
    pod 'Siren'
    pod 'BranchSDK'
    pod 'Ably'
    pod 'Reachability'
    pod 'GoogleSignIn'
    pod 'Amplitude', '8.17.1'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
            end
        end
    end
end