[versions]
kotlin = "1.9.10"
coroutines = "1.7.3"
compose = "1.5.1"
koin = "3.5.0"

[libraries]
#firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "32.3.1" }
firebase-common = { group = "com.google.firebase", name = "firebase-common-ktx" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }

#koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }